## Deliverable 2. Create a Customer Travel Destinations Map.

In [96]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import json
import numpy as np

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [97]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Resources/WeatherPy_database.csv")
city_data_df

,City,Country,Lat,Lon,Max Temp,% Humidity,% Cloudiness,Wind Speed,Current Description
0,faya,td,18.3851,42.4509,53.71,41.0,24.0,3.42,few clouds
1,east london,za,-33.0153,27.9116,58.26,92.0,100.0,12.37,moderate rain
2,umzimvubu,za,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,sola,vu,-13.8833,167.5500,82.04,74.0,5.0,13.20,clear sky
4,changping,cn,40.2186,116.2197,40.64,62.0,1.0,12.91,clear sky
...,...,...,...,...,...,...,...,...,...
1995,mabamba,tz,-3.5983,30.5019,63.18,58.0,82.0,2.62,broken clouds
1996,berndorf,at,47.9457,16.1097,45.66,84.0,7.0,4.23,clear sky
1997,janossomorja,hu,47.7862,17.1360,44.82,67.0,100.0,9.91,overcast clouds
1998,ikeda,jp,34.8221,135.4298,64.11,93.0,75.0,13.80,broken clouds
1999,gobo,jp,33.8833,135.1500,64.38,75.0,88.0,24.23,overcast clouds

In [98]:
# 1a. Determine if there are any empty rows.
# city_data_df.shape[0]
# np.where(city_data_df.applymap(lambda x: x == ''))
city_data_drop_na_df = city_data_df.dropna(axis=0,how='any')
print(f'empty rows {len(city_data_df) - len(city_data_drop_na_df)}')

empty rows 129

In [99]:
city_no_empty_df = city_data_df.dropna()
city_no_empty_df

,City,Country,Lat,Lon,Max Temp,% Humidity,% Cloudiness,Wind Speed,Current Description
0,faya,td,18.3851,42.4509,53.71,41.0,24.0,3.42,few clouds
1,east london,za,-33.0153,27.9116,58.26,92.0,100.0,12.37,moderate rain
3,sola,vu,-13.8833,167.5500,82.04,74.0,5.0,13.20,clear sky
4,changping,cn,40.2186,116.2197,40.64,62.0,1.0,12.91,clear sky
5,shunyi,cn,40.1250,116.6453,40.95,38.0,0.0,15.66,clear sky
...,...,...,...,...,...,...,...,...,...
1995,mabamba,tz,-3.5983,30.5019,63.18,58.0,82.0,2.62,broken clouds
1996,berndorf,at,47.9457,16.1097,45.66,84.0,7.0,4.23,clear sky
1997,janossomorja,hu,47.7862,17.1360,44.82,67.0,100.0,9.91,overcast clouds
1998,ikeda,jp,34.8221,135.4298,64.11,93.0,75.0,13.80,broken clouds
1999,gobo,jp,33.8833,135.1500,64.38,75.0,88.0,24.23,overcast clouds

In [100]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
print("Enter Minimum Temp:", end=' ')
min_temp = input() 
print("Enter Maximum Temp:", end=' ')
max_temp = input() 
print(f'Min Temp:{min_temp} Max Temp:{max_temp}')

Enter Minimum Temp: 66
Enter Maximum Temp: 72
Min Temp:66 Max Temp:72

In [101]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
city_data_temp_filter_df = city_no_empty_df.loc[(city_no_empty_df["Max Temp"] > float(min_temp)) & (city_no_empty_df["Max Temp"] <= float(max_temp))]
city_data_temp_filter_df

,City,Country,Lat,Lon,Max Temp,% Humidity,% Cloudiness,Wind Speed,Current Description
21,arraial do cabo,br,-22.9661,-42.0278,71.56,88.0,75.0,2.30,broken clouds
41,puerto ayora,ec,-0.7393,-90.3518,69.62,79.0,57.0,8.25,broken clouds
98,ponta do sol,cv,32.6667,-17.1000,68.63,69.0,11.0,3.38,few clouds
99,luwingu,zm,-10.2621,29.9271,67.80,45.0,85.0,4.07,overcast clouds
100,kasama,zm,-10.2129,31.1808,67.23,53.0,87.0,3.36,overcast clouds
...,...,...,...,...,...,...,...,...,...
1974,calimete,cu,22.5333,-80.9061,68.14,82.0,0.0,7.27,clear sky
1975,encrucijada,cu,22.6169,-79.8711,66.96,78.0,0.0,6.58,clear sky
1990,mpanda,tz,-6.3655,31.0409,68.16,52.0,85.0,3.02,overcast clouds
1991,mbandaka,cd,0.0487,18.2603,71.85,89.0,100.0,1.10,overcast clouds
1992,bongandanga,cd,1.5000,21.0500,71.24,89.0,17.0,2.01,few clouds

In [102]:
# 4a. Determine if there are any empty rows.
# city_data_temp_filter_df.shape[0]
# np.where(city_data_temp_filter_df.applymap(lambda x: x == ''))
city_data_temp_filter_drop_df = city_data_temp_filter_df.dropna(axis=0,how='any')
print(f'empty rows {len(city_data_temp_filter_drop_df) - len(city_data_temp_filter_df)}')

empty rows 0

In [118]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = city_data_temp_filter_drop_df
clean_df

,City,Country,Lat,Lon,Max Temp,% Humidity,% Cloudiness,Wind Speed,Current Description
21,arraial do cabo,br,-22.9661,-42.0278,71.56,88.0,75.0,2.30,broken clouds
41,puerto ayora,ec,-0.7393,-90.3518,69.62,79.0,57.0,8.25,broken clouds
98,ponta do sol,cv,32.6667,-17.1000,68.63,69.0,11.0,3.38,few clouds
99,luwingu,zm,-10.2621,29.9271,67.80,45.0,85.0,4.07,overcast clouds
100,kasama,zm,-10.2129,31.1808,67.23,53.0,87.0,3.36,overcast clouds
...,...,...,...,...,...,...,...,...,...
1974,calimete,cu,22.5333,-80.9061,68.14,82.0,0.0,7.27,clear sky
1975,encrucijada,cu,22.6169,-79.8711,66.96,78.0,0.0,6.58,clear sky
1990,mpanda,tz,-6.3655,31.0409,68.16,52.0,85.0,3.02,overcast clouds
1991,mbandaka,cd,0.0487,18.2603,71.85,89.0,100.0,1.10,overcast clouds
1992,bongandanga,cd,1.5000,21.0500,71.24,89.0,17.0,2.01,few clouds

In [119]:
# # 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lon"]].copy()
# hotel_df
# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df
# hotel_df.loc[:,"Hotel Name"] = "NaN"

# clean_cp_df = clean_df
# # clean_cp_df["Hotel Name"] = ""
# # clean_cp_df.loc[:,"Hotel Name"] = "NaN"
# clean_cp_df.insert(1, 'Hotel Name', 'NaN')
# # hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lon","Hotel Name"]].copy()
# # hotel_df
# # clean_cp_df
# clean_df

,City,Country,Max Temp,Current Description,Lat,Lon,Hotel Name
21,arraial do cabo,br,71.56,broken clouds,-22.9661,-42.0278,
41,puerto ayora,ec,69.62,broken clouds,-0.7393,-90.3518,
98,ponta do sol,cv,68.63,few clouds,32.6667,-17.1000,
99,luwingu,zm,67.80,overcast clouds,-10.2621,29.9271,
100,kasama,zm,67.23,overcast clouds,-10.2129,31.1808,
...,...,...,...,...,...,...,...
1974,calimete,cu,68.14,clear sky,22.5333,-80.9061,
1975,encrucijada,cu,66.96,clear sky,22.6169,-79.8711,
1990,mpanda,tz,68.16,overcast clouds,-6.3655,31.0409,
1991,mbandaka,cd,71.85,overcast clouds,0.0487,18.2603,
1992,bongandanga,cd,71.24,few clouds,1.5000,21.0500,

In [120]:
# target_type = "lodging"

# city_coords = "47.6062095,-122.3320708"
# print(f'Base:{city_coords}')
# #print(f'1992th:{city_coords}')
# city_coords = f"{hotel_df.iloc[2,4]},{hotel_df.iloc[2,5]}"
# print(f'2th:{city_coords}')
# radius = 5000

In [121]:
# rewrite params dict
params = {
#    "location": "-27.597128608565413,-100.51480592796446", # Did not work, because input to nearest city did not give any result
#    "location": "-9.8,-139.0333", # Approach works
    "location": "50.6996,-127.4199", # Approach works
    
#    "location": "39.952583,-75.16522",  # philadelphia coords
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

params = {
    "location": "39.952583,-75.16522",  # philadelphia coords
    "rankby": "distance",
    "type": "lodging",
    "key": g_key
}

# params = {
#     "location": city_coords,
#     "keyword": target_type,
#     "radius": radius,
#     "key": g_key
# }

# Build URL using the Google Maps API
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

print("Dry run : Establish valid Entry")

# Run request
response = requests.get(base_url, params)
city_hotels_resp = response.json()
city_hotels_resp
print(response.status_code)
# # Print the JSON (pretty printed)
# print(json.dumps(city_hotels_resp, indent=4, sort_keys=True))

Dry run : Establish valid Entry
200

In [123]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "location": city_coords,
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():

    # 6c. Get latitude and longitude from DataFrame
    city_coords = f"{row[4]},{row[5]}"
    params = {
        "location": city_coords,
        "radius": 5000,
        "type": "lodging",
        "key": g_key
    }

    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    try:
        response = requests.get(base_url, params)
        city_hotels_resp = response.json()
    except:
        city_hotels_resp = {
            "html_attributions": [],
            "results": [],
            "status": "ZERO_RESULTS"
        }
        

    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    # if ( city_hotels_resp["status"] != "ZERO_RESULTS" and city_hotels_resp["status"] != "UNKNOWN_ERROR"):
    if ( response.status_code == 200 ):
        try:
            hotel_df.at[index,'Hotel Name'] = city_hotels_resp["results"][0]["name"]
        except:
            hotel_df.at[index,'Hotel Name'] = "NaN"
    else:
        hotel_df.at[index,'Hotel Name'] = "NaN"

# hotel_df["Hotel Name"] = hotel_name_list
hotel_df

,City,Country,Max Temp,Current Description,Lat,Lon,Hotel Name
21,arraial do cabo,br,71.56,broken clouds,-22.9661,-42.0278,Pousada Porto Praia
41,puerto ayora,ec,69.62,broken clouds,-0.7393,-90.3518,Finch Bay Galapagos Hotel
98,ponta do sol,cv,68.63,few clouds,32.6667,-17.1000,Hotel do Campo
99,luwingu,zm,67.80,overcast clouds,-10.2621,29.9271,"MR.C SIMON CHABALA (Maje, Home Place)"
100,kasama,zm,67.23,overcast clouds,-10.2129,31.1808,Kalebalika Cottages
...,...,...,...,...,...,...,...
1974,calimete,cu,68.14,clear sky,22.5333,-80.9061,NaN
1975,encrucijada,cu,66.96,clear sky,22.6169,-79.8711,Hostal La Terraza
1990,mpanda,tz,68.16,overcast clouds,-6.3655,31.0409,CH Hotel - Mpanda
1991,mbandaka,cd,71.85,overcast clouds,0.0487,18.2603,Guest House Epervier
1992,bongandanga,cd,71.24,few clouds,1.5000,21.0500,NaN

In [112]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df.dropna(axis=0,how='any')
# dropna(axis=0, subset = [, how='any', thresh=None, 
clean_hotel_df

,City,Country,Max Temp,Current Description,Lat,Lon,Hotel Name
21,arraial do cabo,br,71.56,broken clouds,-22.9661,-42.0278,Pousada Porto Praia
41,puerto ayora,ec,69.62,broken clouds,-0.7393,-90.3518,Finch Bay Galapagos Hotel
98,ponta do sol,cv,68.63,few clouds,32.6667,-17.1000,Hotel do Campo
99,luwingu,zm,67.80,overcast clouds,-10.2621,29.9271,"MR.C SIMON CHABALA (Maje, Home Place)"
100,kasama,zm,67.23,overcast clouds,-10.2129,31.1808,Kalebalika Cottages
...,...,...,...,...,...,...,...
1974,calimete,cu,68.14,clear sky,22.5333,-80.9061,NaN
1975,encrucijada,cu,66.96,clear sky,22.6169,-79.8711,Hostal La Terraza
1990,mpanda,tz,68.16,overcast clouds,-6.3655,31.0409,CH Hotel - Mpanda
1991,mbandaka,cd,71.85,overcast clouds,0.0487,18.2603,Guest House Epervier
1992,bongandanga,cd,71.24,few clouds,1.5000,21.0500,NaN

In [189]:
# 8a. Create the output File (CSV)
output_data_file = "../Resources/WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [187]:
clean_hotel_data_df = pd.read_csv(output_data_file)
clean_hotel_data_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lon,Hotel Name
0,21,arraial do cabo,br,71.56,broken clouds,-22.9661,-42.0278,Pousada Porto Praia
1,41,puerto ayora,ec,69.62,broken clouds,-0.7393,-90.3518,Finch Bay Galapagos Hotel
2,98,ponta do sol,cv,68.63,few clouds,32.6667,-17.1000,Hotel do Campo
3,99,luwingu,zm,67.80,overcast clouds,-10.2621,29.9271,"MR.C SIMON CHABALA (Maje, Home Place)"
4,100,kasama,zm,67.23,overcast clouds,-10.2129,31.1808,Kalebalika Cottages
...,...,...,...,...,...,...,...,...
197,1974,calimete,cu,68.14,clear sky,22.5333,-80.9061,NaN
198,1975,encrucijada,cu,66.96,clear sky,22.6169,-79.8711,Hostal La Terraza
199,1990,mpanda,tz,68.16,overcast clouds,-6.3655,31.0409,CH Hotel - Mpanda
200,1991,mbandaka,cd,71.85,overcast clouds,0.0487,18.2603,Guest House Epervier
201,1992,bongandanga,cd,71.24,few clouds,1.5000,21.0500,NaN

In [188]:
clean_hotel_df = clean_hotel_df.dropna(axis=0,how='any')
clean_hotel_df

,City,Country,Max Temp,Current Description,Lat,Lon,Hotel Name
21,arraial do cabo,br,71.56,broken clouds,-22.9661,-42.0278,Pousada Porto Praia
41,puerto ayora,ec,69.62,broken clouds,-0.7393,-90.3518,Finch Bay Galapagos Hotel
98,ponta do sol,cv,68.63,few clouds,32.6667,-17.1000,Hotel do Campo
99,luwingu,zm,67.80,overcast clouds,-10.2621,29.9271,"MR.C SIMON CHABALA (Maje, Home Place)"
100,kasama,zm,67.23,overcast clouds,-10.2129,31.1808,Kalebalika Cottages
...,...,...,...,...,...,...,...
1974,calimete,cu,68.14,clear sky,22.5333,-80.9061,NaN
1975,encrucijada,cu,66.96,clear sky,22.6169,-79.8711,Hostal La Terraza
1990,mpanda,tz,68.16,overcast clouds,-6.3655,31.0409,CH Hotel - Mpanda
1991,mbandaka,cd,71.85,overcast clouds,0.0487,18.2603,Guest House Epervier
1992,bongandanga,cd,71.24,few clouds,1.5000,21.0500,NaN

In [183]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """Hotel Name:{}{}{} City:{}{}{} Country:{}{}{} Curent Weather:{}{} and {} F"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format('<br/>',row[6],'<br/>','<br/>',row[0],'<br/>','<br/>',row[1],'<br/>','<br/>',row[3],row[2]) for index, row in clean_hotel_df.iterrows()]
hotel_info

['Hotel Name:<br/>Pousada Porto Praia<br/> City:<br/>arraial do cabo<br/> Country:<br/>br<br/> Curent Weather:<br/>broken clouds and 71.56 F',
 'Hotel Name:<br/>Finch Bay Galapagos Hotel<br/> City:<br/>puerto ayora<br/> Country:<br/>ec<br/> Curent Weather:<br/>broken clouds and 69.62 F',
 'Hotel Name:<br/>Hotel do Campo<br/> City:<br/>ponta do sol<br/> Country:<br/>cv<br/> Curent Weather:<br/>few clouds and 68.63 F',
 'Hotel Name:<br/>MR.C SIMON CHABALA (Maje, Home Place)<br/> City:<br/>luwingu<br/> Country:<br/>zm<br/> Curent Weather:<br/>overcast clouds and 67.8 F',
 'Hotel Name:<br/>Kalebalika Cottages<br/> City:<br/>kasama<br/> Country:<br/>zm<br/> Curent Weather:<br/>overcast clouds and 67.23 F',
 'Hotel Name:<br/>Foundation Taaj Asala for Historical Research and Archeology<br/> City:<br/>sabha<br/> Country:<br/>ly<br/> Curent Weather:<br/>overcast clouds and 69.12 F',
 'Hotel Name:<br/>Hotel Yugaf Inn Okinawa<br/> City:<br/>nago<br/> Country:<br/>jp<br/> Curent Weather:<br/>overcast clouds and 69.87 F',
 'Hotel Name:<br/>Brijwasi Lands Inn<br/> City:<br/>mathura<br/> Country:<br/>in<br/> Curent Weather:<br/>few clouds and 67.12 F',
 'Hotel Name:<br/>Laucky house<br/> City:<br/>sakit<br/> Country:<br/>in<br/> Curent Weather:<br/>clear sky and 66.22 F',
 'Hotel Name:<br/>Shellharbour Resort & Conference Centre<br/> City:<br/>flinders<br/> Country:<br/>au<br/> Curent Weather:<br/>overcast clouds and 71.06 F',
 'Hotel Name:<br/>Foreshore Motor Inn<br/> City:<br/>whyalla<br/> Country:<br/>au<br/> Curent Weather:<br/>scattered clouds and 66.09 F',
 'Hotel Name:<br/>Hotel Conceição<br/> City:<br/>linhares<br/> Country:<br/>br<br/> Curent Weather:<br/>broken clouds and 71.2 F',
 'Hotel Name:<br/>Bushido Lodge<br/> City:<br/>kaeo<br/> Country:<br/>nz<br/> Curent Weather:<br/>few clouds and 69.21 F',
 'Hotel Name:<br/>Hotel San Isidro Oficial<br/> City:<br/>pisco<br/> Country:<br/>pe<br/> Curent Weather:<br/>scattered clouds and 66.25 F',
 'Hotel Name:<br/>Hotel do Campo<br/> City:<br/>ponta do sol<br/> Country:<br/>pt<br/> Curent Weather:<br/>few clouds and 68.63 F',
 'Hotel Name:<br/>ibis Styles Karratha<br/> City:<br/>karratha<br/> Country:<br/>au<br/> Curent Weather:<br/>few clouds and 71.26 F',
 'Hotel Name:<br/>Juvinal Martin<br/> City:<br/>airai<br/> Country:<br/>pw<br/> Curent Weather:<br/>overcast clouds and 70.93 F',
 'Hotel Name:<br/>Complejo Turístico Farelluk<br/> City:<br/>san vicente<br/> Country:<br/>ph<br/> Curent Weather:<br/>scattered clouds and 66.33 F',
 'Hotel Name:<br/>Southern Beach Hotel & Resort Okinawa<br/> City:<br/>itoman<br/> Country:<br/>jp<br/> Curent Weather:<br/>broken clouds and 69.82 F',
 'Hotel Name:<br/>کافی نت پارس<br/> City:<br/>bandar-e lengeh<br/> Country:<br/>ir<br/> Curent Weather:<br/>clear sky and 69.91 F',
 'Hotel Name:<br/>Hotel Sunrise Choshi<br/> City:<br/>hasaki<br/> Country:<br/>jp<br/> Curent Weather:<br/>overcast clouds and 68.29 F',
 'Hotel Name:<br/>Lazy River Motor Inn<br/> City:<br/>swan hill<br/> Country:<br/>au<br/> Curent Weather:<br/>broken clouds and 67.96 F',
 'Hotel Name:<br/>Riviana Motel<br/> City:<br/>deniliquin<br/> Country:<br/>au<br/> Curent Weather:<br/>broken clouds and 68.5 F',
 'Hotel Name:<br/>صاحبة الفخامة<br/> City:<br/>jalu<br/> Country:<br/>ly<br/> Curent Weather:<br/>overcast clouds and 67.93 F',
 'Hotel Name:<br/>Hotel Chik Chik Namibe<br/> City:<br/>namibe<br/> Country:<br/>ao<br/> Curent Weather:<br/>clear sky and 68.14 F',
 'Hotel Name:<br/>Hotel Peace Land Ishigakijima<br/> City:<br/>ishigaki<br/> Country:<br/>jp<br/> Curent Weather:<br/>broken clouds and 68.13 F',
 'Hotel Name:<br/>Hotel Atoll Emerald Miyakojima<br/> City:<br/>hirara<br/> Country:<br/>jp<br/> Curent Weather:<br/>broken clouds and 67.86 F',
 'Hotel Name:<br/>Ramanandraibe Andapa<br/> City:<br/>andapa<br/> Country:<br/>mg<br/> Curent Weather:<br/>scattered clouds and 67.33 F',
 'Hotel Name:<br/>Macaúbas Palace Hotel<br/> City:<br/>macaubas<br/> Country:<br/>br<br/> Curent Weather:<br/>overcast clouds and 69.44 F',
 'Hotel Name:<br/>Chabanga Lodge iSpot<br/> City:<br/>ndola<br/> Country:<br/>zm<br/> Curent Weather:<br/>broken clouds and 71.46 F',
 "Hotel Name:<br/>The Kabaso's<br/> City:<br/>serenje<br/> Country:<br/>zm<br/> Curent Weather:<br/>scattered clouds and 66.31 F",
 'Hotel Name:<br/>The Sebel Kiama Harbourside<br/> City:<br/>kiama<br/> Country:<br/>au<br/> Curent Weather:<br/>overcast clouds and 71.26 F',
 'Hotel Name:<br/>Chembe Nsofu<br/> City:<br/>kawambwa<br/> Country:<br/>zm<br/> Curent Weather:<br/>broken clouds and 67.55 F',
 'Hotel Name:<br/>Government Guest House<br/> City:<br/>mporokoso<br/> Country:<br/>zm<br/> Curent Weather:<br/>broken clouds and 67.03 F',
 'Hotel Name:<br/>NaN<br/> City:<br/>ouadda<br/> Country:<br/>cf<br/> Curent Weather:<br/>overcast clouds and 71.42 F',
 'Hotel Name:<br/>Hospitality Carnarvon<br/> City:<br/>carnarvon<br/> Country:<br/>au<br/> Curent Weather:<br/>scattered clouds and 69.87 F',
 'Hotel Name:<br/>Ghanzi Farmhouse<br/> City:<br/>ghanzi<br/> Country:<br/>bw<br/> Curent Weather:<br/>overcast clouds and 68.18 F',
 'Hotel Name:<br/>Residencia Aveiro<br/> City:<br/>mbutuy<br/> Country:<br/>py<br/> Curent Weather:<br/>few clouds and 70.02 F',
 'Hotel Name:<br/>139 on Munnik Guest House<br/> City:<br/>louis trichardt<br/> Country:<br/>za<br/> Curent Weather:<br/>few clouds and 71.19 F',
 'Hotel Name:<br/>Monte Carlo<br/> City:<br/>villa carlos paz<br/> Country:<br/>ar<br/> Curent Weather:<br/>clear sky and 66.25 F',
 'Hotel Name:<br/>Hotel Sussex<br/> City:<br/>cordoba<br/> Country:<br/>ar<br/> Curent Weather:<br/>clear sky and 69.6 F',
 'Hotel Name:<br/>Sir Joe guest Inn<br/> City:<br/>kafanchan<br/> Country:<br/>ng<br/> Curent Weather:<br/>broken clouds and 70.05 F',
 'Hotel Name:<br/>Silk Suites<br/> City:<br/>jos<br/> Country:<br/>ng<br/> Curent Weather:<br/>overcast clouds and 66.81 F',
 'Hotel Name:<br/>Palmar Hotel Casino<br/> City:<br/>concordia<br/> Country:<br/>ar<br/> Curent Weather:<br/>clear sky and 71.78 F',
 "Hotel Name:<br/>Ron and Tony's Bed & Breakfast<br/> City:<br/>tuatapere<br/> Country:<br/>nz<br/> Curent Weather:<br/>overcast clouds and 68.52 F",
 'Hotel Name:<br/>NaN<br/> City:<br/>bukama<br/> Country:<br/>cd<br/> Curent Weather:<br/>broken clouds and 71.2 F',
 'Hotel Name:<br/>Tibesti Hotel<br/> City:<br/>benghazi<br/> Country:<br/>ly<br/> Curent Weather:<br/>overcast clouds and 71.1 F',
 'Hotel Name:<br/>Lagrota restaurant<br/> City:<br/>tukrah<br/> Country:<br/>ly<br/> Curent Weather:<br/>overcast clouds and 69.26 F',
 'Hotel Name:<br/>Hotel La Joya Isla Mujeres<br/> City:<br/>isla mujeres<br/> Country:<br/>mx<br/> Curent Weather:<br/>overcast clouds and 71.65 F',
 'Hotel Name:<br/>Chikangwe Guest houses<br/> City:<br/>karoi<br/> Country:<br/>zw<br/> Curent Weather:<br/>clear sky and 71.06 F',
 'Hotel Name:<br/>Mayfair Lodges and Restaurant<br/> City:<br/>bindura<br/> Country:<br/>zw<br/> Curent Weather:<br/>overcast clouds and 68.18 F',
 'Hotel Name:<br/>Praia Hotel Imbituba<br/> City:<br/>imbituba<br/> Country:<br/>br<br/> Curent Weather:<br/>overcast clouds and 68.83 F',
 'Hotel Name:<br/>Banjanay Hotel<br/> City:<br/>xuddur<br/> Country:<br/>so<br/> Curent Weather:<br/>scattered clouds and 69.64 F',
 'Hotel Name:<br/>Floresta Amazonica Hotel<br/> City:<br/>alta floresta<br/> Country:<br/>br<br/> Curent Weather:<br/>overcast clouds and 71.46 F',
 'Hotel Name:<br/>NaN<br/> City:<br/>adrar<br/> Country:<br/>dz<br/> Curent Weather:<br/>broken clouds and 67.5 F',
 'Hotel Name:<br/>Grand Hotel<br/> City:<br/>reconquista<br/> Country:<br/>ar<br/> Curent Weather:<br/>clear sky and 71.28 F',
 'Hotel Name:<br/>Toyoko Inn Oyama-eki Higashi-guchi No.1<br/> City:<br/>oyama<br/> Country:<br/>jp<br/> Curent Weather:<br/>overcast clouds and 68.88 F',
 'Hotel Name:<br/>Shimoda Tokyu Hotel<br/> City:<br/>shimoda<br/> Country:<br/>jp<br/> Curent Weather:<br/>overcast clouds and 70.16 F',
 'Hotel Name:<br/>Alpamayo<br/> City:<br/>salitral<br/> Country:<br/>pe<br/> Curent Weather:<br/>overcast clouds and 70.02 F',
 'Hotel Name:<br/>NaN<br/> City:<br/>micomeseng<br/> Country:<br/>gq<br/> Curent Weather:<br/>overcast clouds and 68.9 F',
 'Hotel Name:<br/>NaN<br/> City:<br/>taoudenni<br/> Country:<br/>ml<br/> Curent Weather:<br/>overcast clouds and 66.42 F',
 'Hotel Name:<br/>Countryside Inn Wharton, TX<br/> City:<br/>wharton<br/> Country:<br/>us<br/> Curent Weather:<br/>clear sky and 70.09 F',
 'Hotel Name:<br/>Comfort Inn & Suites Texas City<br/> City:<br/>galveston<br/> Country:<br/>us<br/> Curent Weather:<br/>clear sky and 70.18 F',
 'Hotel Name:<br/>Ramada by Wyndham Enid<br/> City:<br/>enid<br/> Country:<br/>us<br/> Curent Weather:<br/>clear sky and 66.31 F',
 'Hotel Name:<br/>Sonner Motor Inn<br/> City:<br/>winfield<br/> Country:<br/>us<br/> Curent Weather:<br/>clear sky and 67.55 F',
 'Hotel Name:<br/>Hotel los Algarrobos<br/> City:<br/>puerto baquerizo moreno<br/> Country:<br/>ec<br/> Curent Weather:<br/>few clouds and 68.68 F',
 'Hotel Name:<br/>Grand Hotel President<br/> City:<br/>locri<br/> Country:<br/>it<br/> Curent Weather:<br/>overcast clouds and 71.51 F',
 'Hotel Name:<br/>Hotel Summery<br/> City:<br/>lixourion<br/> Country:<br/>gr<br/> Curent Weather:<br/>overcast clouds and 66.06 F',
 'Hotel Name:<br/>Sangthong Resort<br/> City:<br/>chiang klang<br/> Country:<br/>th<br/> Curent Weather:<br/>broken clouds and 70.93 F',
 'Hotel Name:<br/>NaN<br/> City:<br/>boende<br/> Country:<br/>cd<br/> Curent Weather:<br/>light rain and 70.07 F',
 'Hotel Name:<br/>NaN<br/> City:<br/>yangambi<br/> Country:<br/>cd<br/> Curent Weather:<br/>few clouds and 69.87 F',
 'Hotel Name:<br/>Hotel Rinconcito Verde<br/> City:<br/>paraiso<br/> Country:<br/>mx<br/> Curent Weather:<br/>broken clouds and 67.06 F',
 'Hotel Name:<br/>Tolaga Bay Motel<br/> City:<br/>tolaga bay<br/> Country:<br/>nz<br/> Curent Weather:<br/>clear sky and 66.31 F',
 'Hotel Name:<br/>Ahipara Holiday Park<br/> City:<br/>ahipara<br/> Country:<br/>nz<br/> Curent Weather:<br/>few clouds and 68.9 F',
 "Hotel Name:<br/>Anil's Inn<br/> City:<br/>matale<br/> Country:<br/>lk<br/> Curent Weather:<br/>overcast clouds and 70.34 F",
 'Hotel Name:<br/>Hotel Los Andes<br/> City:<br/>los andes<br/> Country:<br/>cl<br/> Curent Weather:<br/>clear sky and 70.57 F',
 'Hotel Name:<br/>BON Hotel Waterfront Richards Bay<br/> City:<br/>richards bay<br/> Country:<br/>za<br/> Curent Weather:<br/>overcast clouds and 68.07 F',
 'Hotel Name:<br/>Hotel Mirage<br/> City:<br/>vilhena<br/> Country:<br/>br<br/> Curent Weather:<br/>overcast clouds and 67.6 F',
 'Hotel Name:<br/>Comfort Inn & Suites Warragul<br/> City:<br/>warragul<br/> Country:<br/>au<br/> Curent Weather:<br/>clear sky and 67.44 F',
 'Hotel Name:<br/>"Plantation Bed and Breakfast<br/> City:<br/>saint-joseph<br/> Country:<br/>re<br/> Curent Weather:<br/>clear sky and 71.96 F',
 'Hotel Name:<br/>Hotel Morotin<br/> City:<br/>santa maria<br/> Country:<br/>cv<br/> Curent Weather:<br/>clear sky and 69.1 F',
 'Hotel Name:<br/>El Medina<br/> City:<br/>nouadhibou<br/> Country:<br/>mr<br/> Curent Weather:<br/>clear sky and 66.18 F',
 'Hotel Name:<br/>Hotel Aconcagua<br/> City:<br/>presidencia roque saenz pena<br/> Country:<br/>ar<br/> Curent Weather:<br/>clear sky and 70.14 F',
 'Hotel Name:<br/>Desert Palms Alice Springs<br/> City:<br/>alice springs<br/> Country:<br/>au<br/> Curent Weather:<br/>scattered clouds and 71.15 F',
 'Hotel Name:<br/>Ilha Flat Hotel<br/> City:<br/>ilhabela<br/> Country:<br/>br<br/> Curent Weather:<br/>overcast clouds and 70.11 F',
 'Hotel Name:<br/>Eastwood Guesthouse<br/> City:<br/>ialibu<br/> Country:<br/>pg<br/> Curent Weather:<br/>few clouds and 66.83 F',
 'Hotel Name:<br/>Days Inn by Wyndham Duncan<br/> City:<br/>duncan<br/> Country:<br/>us<br/> Curent Weather:<br/>clear sky and 69.69 F',
 'Hotel Name:<br/>Sevebat<br/> City:<br/>niamtougou<br/> Country:<br/>tg<br/> Curent Weather:<br/>clear sky and 71.44 F',
 'Hotel Name:<br/>محمدالمبروك الاريقط<br/> City:<br/>mizdah<br/> Country:<br/>ly<br/> Curent Weather:<br/>overcast clouds and 67.28 F',
 'Hotel Name:<br/>NaN<br/> City:<br/>nakapiripirit<br/> Country:<br/>ug<br/> Curent Weather:<br/>broken clouds and 67.71 F',
 'Hotel Name:<br/>Orient Apartments<br/> City:<br/>nizwa<br/> Country:<br/>om<br/> Curent Weather:<br/>clear sky and 68.77 F',
 'Hotel Name:<br/>مزرعة راحة النفوس المنزفة<br/> City:<br/>ibra<br/> Country:<br/>om<br/> Curent Weather:<br/>clear sky and 69.8 F',
 'Hotel Name:<br/>Playa Canela Hotel Boutique<br/> City:<br/>la libertad<br/> Country:<br/>sv<br/> Curent Weather:<br/>scattered clouds and 68.97 F',
 'Hotel Name:<br/>RR Plaza<br/> City:<br/>attur<br/> Country:<br/>in<br/> Curent Weather:<br/>overcast clouds and 71.8 F',
 'Hotel Name:<br/>Miramar<br/> City:<br/>miramar<br/> Country:<br/>mx<br/> Curent Weather:<br/>clear sky and 71.62 F',
 'Hotel Name:<br/>Hotel Full Business<br/> City:<br/>mbanza-ngungu<br/> Country:<br/>cd<br/> Curent Weather:<br/>light rain and 68.16 F',
 'Hotel Name:<br/>Motel Bouenguidi<br/> City:<br/>koulamoutou<br/> Country:<br/>ga<br/> Curent Weather:<br/>light rain and 71.58 F',
 'Hotel Name:<br/>NaN<br/> City:<br/>mounana<br/> Country:<br/>ga<br/> Curent Weather:<br/>moderate rain and 70.43 F',
 'Hotel Name:<br/>Kahama Gold Hotel<br/> City:<br/>kahama<br/> Country:<br/>tz<br/> Curent Weather:<br/>broken clouds and 68.22 F',
 'Hotel Name:<br/>御宿商旅-中山館<br/> City:<br/>kaohsiung<br/> Country:<br/>tw<br/> Curent Weather:<br/>overcast clouds and 69.75 F',
 'Hotel Name:<br/>Avila Vista<br/> City:<br/>leopold<br/> Country:<br/>au<br/> Curent Weather:<br/>scattered clouds and 67.46 F',
 'Hotel Name:<br/>NaN<br/> City:<br/>araouane<br/> Country:<br/>ml<br/> Curent Weather:<br/>overcast clouds and 71.78 F',
 'Hotel Name:<br/>Minshuku Agaihama<br/> City:<br/>nishihara<br/> Country:<br/>jp<br/> Curent Weather:<br/>broken clouds and 69.08 F',
 'Hotel Name:<br/>Grand Hotel Río Cuarto<br/> City:<br/>rio cuarto<br/> Country:<br/>ar<br/> Curent Weather:<br/>few clouds and 71.37 F',
 'Hotel Name:<br/>Euskadi Hotel<br/> City:<br/>general pico<br/> Country:<br/>ar<br/> Curent Weather:<br/>overcast clouds and 67.14 F',
 'Hotel Name:<br/>NaN<br/> City:<br/>ananas<br/> Country:<br/>br<br/> Curent Weather:<br/>clear sky and 69.96 F',
 'Hotel Name:<br/>Villa Giuliana<br/> City:<br/>licata<br/> Country:<br/>it<br/> Curent Weather:<br/>overcast clouds and 69.55 F',
 'Hotel Name:<br/>Eden Rock Lodge<br/> City:<br/>inyonga<br/> Country:<br/>tz<br/> Curent Weather:<br/>overcast clouds and 67.89 F',
 'Hotel Name:<br/>Hotel Fanilo<br/> City:<br/>vangaindrano<br/> Country:<br/>mg<br/> Curent Weather:<br/>broken clouds and 71.51 F',
 'Hotel Name:<br/>Miarina<br/> City:<br/>farafangana<br/> Country:<br/>mg<br/> Curent Weather:<br/>scattered clouds and 71.56 F',
 'Hotel Name:<br/>Desert Gardens Hotel - Ayers Rock Resort<br/> City:<br/>yulara<br/> Country:<br/>au<br/> Curent Weather:<br/>broken clouds and 67.84 F',
 'Hotel Name:<br/>Vahiny Lodge<br/> City:<br/>mananjary<br/> Country:<br/>mg<br/> Curent Weather:<br/>overcast clouds and 70.95 F',
 'Hotel Name:<br/>عمارة السفير<br/> City:<br/>surman<br/> Country:<br/>ly<br/> Curent Weather:<br/>overcast clouds and 70.09 F',
 'Hotel Name:<br/>Hotel Al-Safwa<br/> City:<br/>tripoli<br/> Country:<br/>ly<br/> Curent Weather:<br/>overcast clouds and 71.13 F',
 'Hotel Name:<br/>NaN<br/> City:<br/>campeche<br/> Country:<br/>mx<br/> Curent Weather:<br/>clear sky and 69.1 F',
 'Hotel Name:<br/>Hotel Goverdhan Tourist Complex<br/> City:<br/>fatehpur sikri<br/> Country:<br/>in<br/> Curent Weather:<br/>clear sky and 66.52 F',
 'Hotel Name:<br/>Vila Nova Hotel<br/> City:<br/>ponta delgada<br/> Country:<br/>pt<br/> Curent Weather:<br/>scattered clouds and 70.5 F',
 'Hotel Name:<br/>NaN<br/> City:<br/>awjilah<br/> Country:<br/>ly<br/> Curent Weather:<br/>overcast clouds and 67.48 F',
 'Hotel Name:<br/>โรงแรมแสงชัย<br/> City:<br/>kuchinarai<br/> Country:<br/>th<br/> Curent Weather:<br/>broken clouds and 69.42 F',
 'Hotel Name:<br/>โรงแรม ริเวอร์ ฟร้อนท์ (Riverfront Hotel)<br/> City:<br/>savannakhet<br/> Country:<br/>la<br/> Curent Weather:<br/>mist and 68.02 F',
 'Hotel Name:<br/>Pestana Bahia Praia<br/> City:<br/>vila franca do campo<br/> Country:<br/>pt<br/> Curent Weather:<br/>overcast clouds and 70.2 F',
 'Hotel Name:<br/>Lingao Ditai Inn<br/> City:<br/>lingao<br/> Country:<br/>cn<br/> Curent Weather:<br/>light rain and 68.07 F',
 'Hotel Name:<br/>Hotel Mision Ciudad Valles<br/> City:<br/>ciudad valles<br/> Country:<br/>mx<br/> Curent Weather:<br/>broken clouds and 71.78 F',
 'Hotel Name:<br/>Hotel Porto Santo & Spa<br/> City:<br/>porto santo<br/> Country:<br/>pt<br/> Curent Weather:<br/>scattered clouds and 67.91 F',
 'Hotel Name:<br/>Dibbo areaمنطقة دبو<br/> City:<br/>kutum<br/> Country:<br/>sd<br/> Curent Weather:<br/>clear sky and 69.37 F',
 'Hotel Name:<br/>Pousada Morro Dos Ventos<br/> City:<br/>chapada dos guimaraes<br/> Country:<br/>br<br/> Curent Weather:<br/>overcast clouds and 69.46 F',
 'Hotel Name:<br/>Pousada e Restaurante Portal da Chapada<br/> City:<br/>iacu<br/> Country:<br/>br<br/> Curent Weather:<br/>overcast clouds and 71.83 F',
 'Hotel Name:<br/>Stúdios Stifler<br/> City:<br/>cruz das almas<br/> Country:<br/>br<br/> Curent Weather:<br/>overcast clouds and 70.18 F',
 'Hotel Name:<br/>McCracken Country Club<br/> City:<br/>victor harbor<br/> Country:<br/>au<br/> Curent Weather:<br/>overcast clouds and 68.47 F',
 'Hotel Name:<br/>New City Top Hotel & Restaurant<br/> City:<br/>minchinabad<br/> Country:<br/>pk<br/> Curent Weather:<br/>clear sky and 66.6 F',
 'Hotel Name:<br/>Hôtel les Nouveaux Jardins Des Tropiques<br/> City:<br/>mbalmayo<br/> Country:<br/>cm<br/> Curent Weather:<br/>overcast clouds and 67.96 F',
 'Hotel Name:<br/>Avenida Palace Hotel<br/> City:<br/>sao joao do paraiso<br/> Country:<br/>br<br/> Curent Weather:<br/>overcast clouds and 67.82 F',
 'Hotel Name:<br/>Pousada San Remo<br/> City:<br/>itambe<br/> Country:<br/>br<br/> Curent Weather:<br/>light rain and 70.16 F',
 'Hotel Name:<br/>Foundation Taaj Asala for Historical Research and Archeology<br/> City:<br/>sabha<br/> Country:<br/>jo<br/> Curent Weather:<br/>overcast clouds and 68.34 F',
 'Hotel Name:<br/>Hotel y Casino del Río General Roca<br/> City:<br/>general roca<br/> Country:<br/>ar<br/> Curent Weather:<br/>clear sky and 72.0 F',
 'Hotel Name:<br/>Hospedaje Ratto<br/> City:<br/>mazamari<br/> Country:<br/>pe<br/> Curent Weather:<br/>overcast clouds and 71.01 F',
 'Hotel Name:<br/>NaN<br/> City:<br/>pangoa<br/> Country:<br/>pe<br/> Curent Weather:<br/>overcast clouds and 68.76 F',
 'Hotel Name:<br/>MR-SAGAR_KUMAR_RTR™<br/> City:<br/>yarada<br/> Country:<br/>in<br/> Curent Weather:<br/>mist and 70.12 F',
 'Hotel Name:<br/>G.lingaraju home<br/> City:<br/>narasannapeta<br/> Country:<br/>in<br/> Curent Weather:<br/>broken clouds and 68.63 F',
 'Hotel Name:<br/>Eng Hiirey House<br/> City:<br/>odweyne<br/> Country:<br/>so<br/> Curent Weather:<br/>overcast clouds and 66.74 F',
 'Hotel Name:<br/>Curubo Hotel<br/> City:<br/>garowe<br/> Country:<br/>so<br/> Curent Weather:<br/>broken clouds and 67.78 F',
 'Hotel Name:<br/>MA 22 LODGE<br/> City:<br/>kapiri mposhi<br/> Country:<br/>zm<br/> Curent Weather:<br/>scattered clouds and 71.8 F',
 'Hotel Name:<br/>Mkushi Police Club<br/> City:<br/>mkushi<br/> Country:<br/>zm<br/> Curent Weather:<br/>few clouds and 69.37 F',
 'Hotel Name:<br/>Kirari Guest House<br/> City:<br/>gushikawa<br/> Country:<br/>jp<br/> Curent Weather:<br/>overcast clouds and 67.62 F',
 'Hotel Name:<br/>Holiday Inn Selma-Swancourt, an IHG Hotel<br/> City:<br/>selma<br/> Country:<br/>us<br/> Curent Weather:<br/>overcast clouds and 66.04 F',
 'Hotel Name:<br/>Hospedaje Costa Bella<br/> City:<br/>sechura<br/> Country:<br/>pe<br/> Curent Weather:<br/>broken clouds and 66.07 F',
 'Hotel Name:<br/>Hotel Zawadi<br/> City:<br/>adjumani<br/> Country:<br/>ug<br/> Curent Weather:<br/>light rain and 66.04 F',

In [184]:
locations = clean_hotel_df[["Lat", "Lon"]]

In [185]:
gmaps.configure(api_key=g_key)
fig = gmaps.figure()
locations = clean_hotel_df[["Lat", "Lon"]]
# marker_layer = gmaps.marker_layer(locations,label=hotel_info)
marker_layer = gmaps.marker_layer(locations,info_box_content=hotel_info,display_info_box=True)
fig.add_layer(marker_layer)
# symbols = gmaps.symbol_layer(
#         locations, fill_color='red', stroke_color='red')
# fig.add_layer(symbols)

In [186]:
# 11a. Add a marker layer for each city to the map. 

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))